// Generated by CoffeeScript 1.8.0
(function() {
  var factorial;

  factorial = function(num) {
    var _factorial;
    if (!/^\d+$/.test(num)) {
      throw 'Error: Not an integer!';
    }
    _factorial = function(num) {
      return (num <= 1 ? 1 : num * _factorial(num - 1));
    };
    return _factorial(num);
  };

  window.factorial = factorial;

}).call(this);

//# sourceMappingURL=sample.js.map
